### ISSUE TITLE
upgrade Readme documentation

### ISSUE THREAD

**Issue by kiroxan** [jowavp/sap-cf-proxy#22]
Dear contributers ,

this project seems to solve a big issue for developers willing to consume on-premise systems locally, but I have a hard time understanding the architecture with the ssh tunnel .

if you can provide more details that would help a lot. i can also blog on it on https://blogs.sap.com once I understand how it works.

thank you

**Comment by gregorwolf** [comment]
Please check if #23 helps you to understand the functionality. In the [README](https://github.com/gregorwolf/sap-cf-proxy/tree/22-documentation#why) of my branch you can see also the picture that I've provided to illustrate the architecture.
