### ISSUE TITLE
Suggestion: Use the @sap-cloud-sdk/core for Destination / Connectivity details

### ISSUE THREAD

**Issue by vfweiss** [jowavp/sap-cf-proxy#5]
As the SAP Cloud SDK Javascript / Typescript is Open Source, I would highly suggest to leverage that for retrieving destination and connectivity information.
For example:
{ getDestinationFromDestinationService } = require('@sap-cloud-sdk/core')
And if Destination has the Proxy type OnPremise, retrieve the Connectivity related headers with:
addProxyConfigurationOnPrem
or if you want the full flow which also accounts for subscriber/provider tenants and all:
{ getDestination } = require('@sap-cloud-sdk/core')

For more see:
https://sap.github.io/cloud-sdk/api/1.39.0/modules/sap_cloud_sdk_core

**Comment by jowavp** [comment]
Hi Vincent,

Thanks for the tip. I will give it a try later.

Kr
Jowa

**Comment by gregorwolf** [comment]
I've started a branch [use-sap-cloud-sdk](https://github.com/gregorwolf/sap-cf-proxy/tree/use-sap-cloud-sdk). But to get a feeling what the getDestination method returns I want to debug and need to provide the VCAP_SERVICES environment variable filled with the date from my default-env.json. Does someone knows a way how to do that?

**Comment by vfweiss** [comment]
@gregorwolf Do you happen to mean xsenv.loadEnv() ?
